apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
## load _profiles/_base first
- ../../_base
## then _profiles/llm-management/_base next
#- ../_base

patches:
- path: ingress-nginx-addons.yaml
- path: kubernetes-dashboard-addons.yaml
- path: weave-gitops-addons.yaml
