apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- kube-vip-repo.yaml
- cert-manager-repo.yaml
- ingress-nginx-repo.yaml
- weave-gitops-repo.yaml
- kubernetes-dashboard-repo.yaml



