apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- gpu-operator-repo.yaml
- knative-istio-repo.yaml
#- knative-operator-repo.yaml
- knative-serving-repo.yaml
- knative-eventing-repo.yaml
- otel-collector-daemon-repo.yaml
- otel-collector-deploy-repo.yaml
- redis-repo.yaml
- kserve-repo.yaml
- nai-helm-repo.yaml
- gptnvd-reference-app-repo.yaml
- kuberay-operator-repo.yaml
- kuberay-cluster-repo.yaml
