apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
## load _profiles/_base first
- ../../_base
## then _profiles/nai-llm-k8s/_base next
- ../_base

patches:
- path: gpu-operator-addons.yaml
- path: cert-manager-addons.yaml
- path: weave-gitops-addons.yaml

