postgresql:
  imagePullSecrets:
  - name: regcred
clickhouse:
  imagePullSecrets:
  - name: regcred

# ingress:
#   enabled: true
#   className: nginx
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt
#   hosts:
#     - host: uptrace.gptmgmt.cloudnative.nvdlab.net
#       paths:
#         - path: /
#           pathType: Prefix
#   tls:
#     - secretName: uptrace-tls
#       hosts:
#         - uptrace.gptmgmt.cloudnative.nvdlab.net
