kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-configs
data:
  cluster_name: "nke-nvd-llm-mgmt-02"
  environment: "prod"
  cluster_profile: "llm-management"  
  kube_vip_ipam_range: "10.50.119.52-10.50.119.53"
  kube_vip_nginx_ingress_ipam: "10.50.119.50/32"
  wildcard_ingress_subdomain: "nke-nvd-llm-mgmt-02.cloudnative.nvdlab.net"
  management_cluster_ingress_subdomain: "nke-nvd-llm-mgmt-02.cloudnative.nvdlab.net"
  aws_route53_dns_zone: "cloudnative.nvdlab.net"
  aws_route53_region: "us-east-1"
  objects_host: "objects.gptnvd.cloudnative.nvdlab.net"
  objects_port: "80"
  objects_region: "us-east-1"
  objects_use_ssl: "true"