apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
components:
- ../../_profiles/llm-workloads/prod
resources:
- cluster-secrets.sops.yaml
- cluster-configs.yaml

# generatorOptions:
#   disableNameSuffixHash: true

# secretGenerator:
# - name: docker-hub-regcred
#   type: kubernetes.io/dockerconfigjson
#   files:
#   - .dockerconfigjson=hub.dockerconfig.json.encrypted
