apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- istio-namespace.yaml
- istio-ingress-class.yaml
- localized-files/github.com/knative/net-istio/releases/download/knative-v1.10.0/release.yaml
