apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
## load _profiles/_base first
- ../../_base
## then _profiles/llm-workloads/_base next
- ../_base

patches:
- path: ingress-nginx-addons.yaml
- path: kubernetes-dashboard-addons.yaml
- path: gpu-operator-addons.yaml
