apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: disabled

resources:
- https://github.com/knative/net-istio/releases/download/knative-v1.10.0/istio.yaml
