apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gc
  annotations:
    kustomize.toolkit.fluxcd.io/force: disabled
  namespace: knative-serving
data:
  max-non-active-revisions: "0"
  min-non-active-revisions: "0"
  retain-since-create-time: "disabled"
  retain-since-last-active-time: "disabled"
