apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-ui-configmap
data:
  viewer-pod-template.json: |-
    {
        "spec": {
          "containers": [
            {
              "env": [
                {
                  "name": "AWS_ACCESS_KEY_ID",
                  "valueFrom": {
                    "secretKeyRef": {
                      "name": "mlpipeline-minio-artifact",
                      "key": "accesskey"
                    }
                  }
                },
                {
                  "name": "AWS_SECRET_ACCESS_KEY",
                  "valueFrom": {
                    "secretKeyRef": {
                      "name": "mlpipeline-minio-artifact",
                      "key": "secretkey"
                    }
                  }
                },
                {
                  "name": "AWS_REGION",
                  "valueFrom": {
                    "configMapKeyRef": {
                      "name": "pipeline-install-config",
                      "key": "objStoreRegion"
                    }
                  }
                }
              ]
            }
          ]
        }
      }
